FROM rocker/tidyverse
MAINTAINER Jonathan Pedroza (cpppedroza@gmail.com)

# Install secret
RUN install2.r --error \
        sf \
        tidycensus \
        leaflet \
        spdep \
        spatialreg \
        rgdal \
        rgeos \
