FROM rocker/tidyverse
MAINTAINER Jonathan Pedroza (cpppedroza@gmail.com)

RUN apt-get update && apt-get install -y \
	libssl-dev \
	&& apt-gen clean \
	&& rm -rf /var/lib/apt/lists/ \
	&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds
	
RUN install2.r --error \
	-r 'http://cran.rstudio.com' \
	googleAuthR \