---
title: "twitter_conference"
author: "JP"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Twitter Conference Findings

## Data & Prep
```{r, include = FALSE}
library(tidyverse)
library(inspectdf)
library(psych)
library(lme4)
library(lmerTest)
library(optimx)

options(max.print = 99999)
options(scipen = 999)
theme_set(theme_minimal())


getwd()

county_icc_2level <- function(multi_model){
  between <- multi_model$vcov[1]
  total <- multi_model$vcov[1] + multi_model$vcov[2]
  
  between/total
}


counties <- function(years){
  
  link <- glue::glue('https://raw.githubusercontent.com/jpedroza1228/dissertation/master/final_data/county{years}_sub.csv')
  
  rio::import(link, setclass = 'tibble')
  
}


county <- map_df(16:20, ~counties(.x))


county <- county %>% 
  dplyr::select(rowid,
                state_fips_code:release_year,
                poor_or_fair_health:access_to_exercise_opportunities,
                preventable_hospital_stays,
                some_college:driving_alone_to_work,
                food_insecurity:uninsured_children,
                median_household_income:percent_rural) %>% 
  rename(year = release_year,
         state = state_abbreviation) %>% 
  mutate(phyact_percent = (physical_inactivity*100),
         ltpa_percent = (100 - phyact_percent)) %>% 
  rename(access_pa = access_to_exercise_opportunities) %>% 
  mutate(smoking_percent = adult_smoking*100,
         obesity_percent = adult_obesity*100,
         access_pa_percent = access_pa*100,
         college_percent = some_college*100,
         unemployment_percent = unemployment*100,
         driving_alone_percent = driving_alone_to_work*100,
         percent_65plus = percent_65_and_older*100,
         latino_percent = percent_hispanic*100,
         rural_percent = percent_rural*100) %>% 
  dplyr::select(-adult_smoking,
                -adult_obesity,
                -access_pa,
                -some_college,
                -unemployment,
                -driving_alone_to_work,
                -percent_65_and_older,
                -percent_hispanic,
                -percent_rural,
                -phyact_percent,
                -physical_inactivity) %>% 
  filter(fips_code != '0') 

county <- county %>% 
  filter(str_detect(fips_code, '000$', negate = TRUE))

county$year_num <- as.numeric(county$year)

ca <- county %>% 
  filter(state == 'CA') %>% 
  mutate(no_name_county = str_replace_all(county_name, '_county', ''))

ca$no_name_county <- str_to_title(ca$no_name_county)
```

## Models
```{r}
preliminary_ltpa_long <- lmer(ltpa_percent ~ year_num +(1 | county_fips_code),data = ca,
                              REML = FALSE,
                                    control = lmerControl(optimizer = 'Nelder_Mead'))

summary(preliminary_ltpa_long)

ltpa_null_icc <- as_tibble(VarCorr(preliminary_ltpa_long))
ltpa_null_icc

county_icc_2level(ltpa_null_icc)


ltpa_long_access <- lmer(ltpa_percent ~ year_num + violent_crime + obesity_percent + median_household_income + rural_percent +
                           access_pa_percent + (1 | county_fips_code), data = ca,
                         REML = FALSE,control = lmerControl(optimizer = 'Nelder_Mead'))

summary(ltpa_long_access)

anova(preliminary_ltpa_long, ltpa_long_access)

ltpa_access_icc <- as_tibble(VarCorr(ltpa_long_access))
ltpa_access_icc

county_icc_2level(ltpa_access_icc)

```

## Visuals Prep

```{r, include = FALSE}

library(ggmap)
library(maps)
library(RColorBrewer)
library(ggrepel)
display.brewer.all()


us <- map_data(map = 'county')

us <- us %>% 
  janitor::clean_names() %>% 
  rename(state = region,
         no_name_county = subregion) 

us$state <- str_replace_all(us$state, pattern = " ", replacement = "_")
us$no_name_county <- str_replace_all(us$no_name_county, pattern = " ", replacement = "_")

us <- us %>% 
  mutate(state = recode(state, 'alabama' = 'AL','alaska' = 'AK','arizona' = 'AZ','arkansas' = 'AR',
                        'california' = 'CA','colorado' = 'CO','connecticut' = 'CT',
                        'delaware' = 'DE',
                        'florida' = 'FL',
                        'georgia' = 'GA',
                        'hawaii' = 'HI',
                        'idaho' = 'ID','illinois' = 'IL','indiana' = 'IN','iowa' = 'IA',
                        'kansas' = 'KS','kentucky' = 'KY',
                        'louisiana' = 'LA',
                        'maine' = 'ME','maryland' = 'MD','massachusetts' = 'MA','michigan' = 'MI','minnesota' = 'MN','mississippi' = 'MS','missouri' = 'MO','montana' = 'MT',
                        'nebraska' = 'NE','nevada' = 'NV','new hampshire' = 'NH','new jersey' = 'NJ','new mexico' = 'NM','new york' = 'NY','north carolina' = 'NC','north dakota' = 'ND',
                        'ohio' = 'OH','oklahoma' = 'OK','oregon' = 'OR',
                        'pennsylvania' = 'PA',
                        'rhode island' = 'RI',
                        'south carolina' = 'SC','south dakota' = 'SD',
                        'tennessee' = 'TN','texas' = 'TX',
                        'utah' = 'UT',
                        'vermont' = 'VT','virginia' = 'VA',
                        'washington' = 'WA','west virginia' = 'WV','wisconsin' = 'WI','wyoming' = 'WY'))

county <- county %>%
  mutate(no_name_county = str_replace_all(county_name, '_county', ''))

visual <- right_join(us, county, by = c('state', 'no_name_county'))

ca_visual <- visual %>% 
  filter(state == 'CA') %>%
  filter(no_name_county != 'california')

library(gganimate)
```


```{r}
ca$main_effects <- predict(ltpa_long_access, newdata = ca)

main_effects_var <- ranef(ltpa_long_access, condVar = TRUE)
main_effects_var <- as.data.frame(main_effects_var)

main_effects_var <- main_effects_var %>% 
  rename(main_effects_term = term,
         county_fips_code = grp,
         main_effects_diff = condval,
         main_effects_se = condsd) %>% 
  mutate(county_fips_code = as.numeric(county_fips_code))

main_effects_var$no_name_county <- unique(ca$no_name_county)

main_effects_var %>% 
ggplot(aes(fct_reorder(no_name_county, main_effects_diff), main_effects_diff)) +
geom_errorbar(aes(ymin = main_effects_diff + qnorm(0.025)*main_effects_se,
                  ymax = main_effects_diff + qnorm(0.975)*main_effects_se)) +
geom_point(aes(color = no_name_county)) +
coord_flip() +
labs(x = ' ',
     y = 'Differences in Leisure-time Physical Activity',
     title = 'Variation in Leisure-time Physical Activity\nAcross California Counties') +
theme(legend.position = 'none')


ca %>% 
  mutate(year = as.factor(year)) %>% 
ggplot(aes(access_pa_percent, main_effects)) +
geom_point(aes(color = year)) +
geom_smooth(color = 'dodgerblue',
            method = 'lm', se = FALSE, size = 1) +
  theme(legend.title = element_blank()) +
  labs(x = 'Access to Physical Activity Opportunities',
       y = 'Leisure-time Physical Activity',
       title = 'The Statewide Association of Access\nand Physical Activity')

```

### Animated Plot

```{r}
ca_animate <- ca_visual %>%
  ggplot(aes(frame = year,
             cumulative = TRUE)) +
  geom_polygon(aes(x = long, y = lat, 
                   group = group, 
                   fill = ltpa_percent),
               color = 'black') +
  scale_fill_gradientn(colors = brewer.pal(n = 5, name = 'RdYlGn')) + 
  theme_classic() +
  transition_time(year) +
  labs(x = 'Longitude',
       y = 'Latitude',
       title = 'Leisure-time Physical Activity\nChange Over Time',
       subtitle = 'Year: {frame_time}') +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(size = 20),
        plot.subtitle = element_text(size = 18))


ca_animate

# anim_save("ltpa_over_time.gif", ca_animate)
```


